name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: '[BUG] '
labels: ['bug', 'triage']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report
        Thank you for taking the time to report a bug. Please provide as much detail as possible to help us resolve the issue.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug you encountered
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide step-by-step instructions to reproduce the issue
      placeholder: |
        1. Open the application
        2. Navigate to specific widget
        3. Perform action
        4. Observe the error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should have happened
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually occurred
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop screenshots here

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Select your operating system
      options:
        - macOS
        - Windows
        - Linux (Ubuntu)
        - Linux (Other)
        - Other
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      placeholder: 'e.g., Chrome 120, Firefox 121, Safari 17'
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you running?
      placeholder: 'e.g., 18.17.0'
    validations:
      required: false

  - type: input
    id: omnigrid-version
    attributes:
      label: Omni-Grid Version
      description: What version of Omni-Grid are you using?
      placeholder: 'e.g., v1.0.0'
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful

  - type: textarea
    id: possible-solution
    attributes:
      label: Possible Solution
      description: Optional - Do you have suggestions on how to fix the issue?
      placeholder: Describe any potential solutions you've considered
