// Shared language list aligned with the DevDocs (DocuHub) documentation set.
// Keep this list in sync across widgets that surface language options.
export const DEV_DOCS_LANGUAGES = [
  'bash',
  'c',
  'clojure',
  'cpp',
  'csharp',
  'css',
  'dart',
  'docker',
  'elixir',
  'erlang',
  'go',
  'graphql',
  'haskell',
  'html',
  'java',
  'javascript',
  'json',
  'kotlin',
  'lua',
  'markdown',
  'node',
  'perl',
  'php',
  'powershell',
  'python',
  'ruby',
  'rust',
  'sass',
  'scala',
  'sql',
  'swift',
  'typescript',
  'yaml',
];
