/**
 * marketplaceCatalog.ts
 *
 * Static catalog of all widgets available in the Omni-Grid marketplace.
 * Core widgets ship with the platform; community widgets are contributed
 * via the developer portal (see docs/developer-portal.md).
 *
 * To add a new community widget submission, append a new entry here with
 * isCore: false and open a pull request following the contribution guide.
 */

import { MarketplaceEntry } from '../types';

export const MARKETPLACE_CATALOG: MarketplaceEntry[] = [
  // ── Utility ──────────────────────────────────────────────────────────────
  {
    id: 'SYSTEM',
    name: 'System Core',
    description:
      'Real-time system log viewer and diagnostics panel. Monitor all Omni-Grid events, layout changes, and API activity.',
    version: '2.1.0',
    author: 'Omni-Grid Core',
    category: 'utility',
    tags: ['system', 'logs', 'diagnostics'],
    downloads: 12400,
    rating: 4.7,
    updatedAt: '2025-02-01',
    changelog: 'v2.1.0: Added live log filtering and color-coded severity levels.',
    isCore: true,
    minGridW: 3,
    minGridH: 4,
  },
  {
    id: 'HELP',
    name: 'Help Desk',
    description: 'Interactive help guide and keyboard shortcut reference for Omni-Grid operators.',
    version: '1.3.0',
    author: 'Omni-Grid Core',
    category: 'utility',
    tags: ['help', 'shortcuts', 'docs'],
    downloads: 9800,
    rating: 4.5,
    updatedAt: '2025-01-15',
    isCore: true,
    minGridW: 3,
    minGridH: 4,
  },
  {
    id: 'TEMPORAL',
    name: 'Temporal Nexus',
    description: 'World clock, timer, stopwatch, and timezone converter in one widget.',
    version: '1.4.0',
    author: 'Omni-Grid Core',
    category: 'utility',
    tags: ['time', 'clock', 'timezone'],
    downloads: 7300,
    rating: 4.6,
    updatedAt: '2025-01-20',
    isCore: true,
    minGridW: 3,
    minGridH: 4,
  },
  {
    id: 'CALC',
    name: 'Quantum Calc',
    description:
      'Advanced calculator with expression history, unit conversion, and scientific mode.',
    version: '1.2.0',
    author: 'Omni-Grid Core',
    category: 'utility',
    tags: ['calculator', 'math', 'science'],
    downloads: 8900,
    rating: 4.4,
    updatedAt: '2024-12-10',
    isCore: true,
    minGridW: 3,
    minGridH: 6,
  },
  {
    id: 'WEATHER',
    name: 'Weather Station',
    description: 'Real-time weather display and forecasts. Powered by OpenWeatherMap.',
    version: '1.5.0',
    author: 'Omni-Grid Core',
    category: 'utility',
    tags: ['weather', 'forecast', 'location'],
    downloads: 6700,
    rating: 4.3,
    updatedAt: '2025-02-10',
    isCore: true,
    minGridW: 3,
    minGridH: 4,
  },
  {
    id: 'CLIPBOARD',
    name: 'Memory Buffer',
    description:
      'Persistent clipboard history with instant recall, search, and drag-and-drop support.',
    version: '1.1.0',
    author: 'Omni-Grid Core',
    category: 'utility',
    tags: ['clipboard', 'history', 'productivity'],
    downloads: 5500,
    rating: 4.5,
    updatedAt: '2025-01-05',
    isCore: true,
    minGridW: 3,
    minGridH: 4,
  },
  {
    id: 'SUDOKU',
    name: 'Sudoku Grid',
    description: 'Classic Sudoku puzzle game with multiple difficulty levels and hint system.',
    version: '1.0.2',
    author: 'Omni-Grid Core',
    category: 'utility',
    tags: ['game', 'puzzle', 'sudoku'],
    downloads: 3400,
    rating: 4.1,
    updatedAt: '2024-11-20',
    isCore: true,
    minGridW: 4,
    minGridH: 6,
  },

  // ── Developer ─────────────────────────────────────────────────────────────
  {
    id: 'TRANSFORMER',
    name: 'Universal Transformer',
    description: 'JSON formatter, base64 encoder/decoder, hash generator, and data transformer.',
    version: '2.3.0',
    author: 'Omni-Grid Core',
    category: 'developer',
    tags: ['json', 'encode', 'decode', 'hash', 'transform'],
    downloads: 15600,
    rating: 4.9,
    updatedAt: '2025-03-01',
    changelog: 'v2.3.0: Added YAML ↔ JSON conversion and MessagePack support.',
    isCore: true,
    minGridW: 4,
    minGridH: 6,
  },
  {
    id: 'DEV_OPTIC',
    name: 'Dev Optic',
    description: 'Regex tester with live match highlighting, capture group inspector, and export.',
    version: '1.6.0',
    author: 'Omni-Grid Core',
    category: 'developer',
    tags: ['regex', 'testing', 'pattern'],
    downloads: 11200,
    rating: 4.7,
    updatedAt: '2025-02-15',
    isCore: true,
    minGridW: 4,
    minGridH: 6,
  },
  {
    id: 'CYBER_EDITOR',
    name: 'Cyber Editor',
    description: 'Multi-tab Monaco-powered code editor with syntax highlighting for 40+ languages.',
    version: '2.0.1',
    author: 'Omni-Grid Core',
    category: 'developer',
    tags: ['editor', 'code', 'monaco', 'ide'],
    downloads: 14800,
    rating: 4.8,
    updatedAt: '2025-03-05',
    isCore: true,
    minGridW: 6,
    minGridH: 8,
  },
  {
    id: 'WEB_TERMINAL',
    name: 'Web Terminal',
    description: 'Browser-based terminal emulator powered by E2B sandbox for safe code execution.',
    version: '1.4.0',
    author: 'Omni-Grid Core',
    category: 'developer',
    tags: ['terminal', 'shell', 'e2b', 'sandbox'],
    downloads: 9900,
    rating: 4.6,
    updatedAt: '2025-02-20',
    isCore: true,
    minGridW: 4,
    minGridH: 6,
  },
  {
    id: 'GIT_PULSE',
    name: 'Git Pulse',
    description:
      'GitHub repository monitor: commits, PRs, issues, and contributor activity at a glance.',
    version: '1.7.0',
    author: 'Omni-Grid Core',
    category: 'developer',
    tags: ['git', 'github', 'vcs', 'devops'],
    downloads: 8300,
    rating: 4.5,
    updatedAt: '2025-02-25',
    isCore: true,
    minGridW: 4,
    minGridH: 6,
  },
  {
    id: 'DOCU_HUB',
    name: 'DocuHub',
    description:
      'Instant documentation browser for popular libraries and languages, powered by DevDocs.',
    version: '1.2.0',
    author: 'Omni-Grid Core',
    category: 'developer',
    tags: ['docs', 'reference', 'devdocs'],
    downloads: 7100,
    rating: 4.4,
    updatedAt: '2025-01-18',
    isCore: true,
    minGridW: 4,
    minGridH: 8,
  },
  {
    id: 'PROJECT_TRACKER',
    name: 'Project Tracker',
    description: 'Lightweight Kanban board for tracking project tasks, milestones, and deadlines.',
    version: '1.3.0',
    author: 'Omni-Grid Core',
    category: 'developer',
    tags: ['kanban', 'tasks', 'project', 'agile'],
    downloads: 6600,
    rating: 4.4,
    updatedAt: '2025-01-10',
    isCore: true,
    minGridW: 6,
    minGridH: 6,
  },

  // ── Finance ───────────────────────────────────────────────────────────────
  {
    id: 'ASSET',
    name: 'Asset Command',
    description:
      'Live stock and crypto price tracker with portfolio view and percentage change indicators.',
    version: '2.1.0',
    author: 'Omni-Grid Core',
    category: 'finance',
    tags: ['stocks', 'crypto', 'portfolio', 'trading'],
    downloads: 13500,
    rating: 4.7,
    updatedAt: '2025-03-10',
    isCore: true,
    minGridW: 3,
    minGridH: 6,
  },
  {
    id: 'VALUTA',
    name: 'Valuta Exchange',
    description: 'Real-time currency converter supporting 150+ fiat and crypto currencies.',
    version: '1.4.0',
    author: 'Omni-Grid Core',
    category: 'finance',
    tags: ['currency', 'forex', 'exchange', 'conversion'],
    downloads: 7800,
    rating: 4.4,
    updatedAt: '2025-02-08',
    isCore: true,
    minGridW: 3,
    minGridH: 4,
  },
  {
    id: 'MARKET',
    name: 'Market Feed',
    description: 'Real-time market data feed with indices, movers, and sector performance.',
    version: '1.6.0',
    author: 'Omni-Grid Core',
    category: 'finance',
    tags: ['market', 'indices', 'stocks', 'feed'],
    downloads: 9200,
    rating: 4.5,
    updatedAt: '2025-03-08',
    isCore: true,
    minGridW: 3,
    minGridH: 6,
  },
  {
    id: 'CHAIN_PULSE',
    name: 'Chain Pulse',
    description:
      'Live DeFi and on-chain analytics: TVL, gas prices, whale alerts, and protocol stats.',
    version: '1.3.0',
    author: 'Omni-Grid Core',
    category: 'finance',
    tags: ['defi', 'blockchain', 'onchain', 'crypto'],
    downloads: 5400,
    rating: 4.2,
    updatedAt: '2025-02-12',
    isCore: true,
    minGridW: 4,
    minGridH: 6,
  },
  {
    id: 'MACRO_NET',
    name: 'Macro Net',
    description:
      'Macroeconomic dashboard: CPI, interest rates, GDP, and central bank policy trackers.',
    version: '1.2.0',
    author: 'Omni-Grid Core',
    category: 'finance',
    tags: ['macro', 'economics', 'rates', 'indicators'],
    downloads: 4100,
    rating: 4.1,
    updatedAt: '2025-01-28',
    isCore: true,
    minGridW: 4,
    minGridH: 6,
  },
  {
    id: 'REG_RADAR',
    name: 'Reg Radar',
    description: 'Regulatory and compliance alert feed for financial markets across jurisdictions.',
    version: '1.1.0',
    author: 'Omni-Grid Core',
    category: 'finance',
    tags: ['compliance', 'regulation', 'legal', 'finance'],
    downloads: 2900,
    rating: 4.0,
    updatedAt: '2025-01-12',
    isCore: true,
    minGridW: 4,
    minGridH: 6,
  },
  {
    id: 'STRATEGIC',
    name: 'Strategic Blueprint',
    description: 'Visual strategy and planning canvas for business objectives, OKRs, and roadmaps.',
    version: '1.2.0',
    author: 'Omni-Grid Core',
    category: 'productivity',
    tags: ['strategy', 'planning', 'okr', 'roadmap'],
    downloads: 5800,
    rating: 4.4,
    updatedAt: '2025-02-05',
    isCore: true,
    minGridW: 6,
    minGridH: 6,
  },

  // ── Creative ──────────────────────────────────────────────────────────────
  {
    id: 'CHROMA_LAB',
    name: 'Chroma Lab',
    description: 'Color palette generator, contrast checker, and gradient designer for UI work.',
    version: '1.5.0',
    author: 'Omni-Grid Core',
    category: 'creative',
    tags: ['color', 'palette', 'design', 'gradient'],
    downloads: 9400,
    rating: 4.7,
    updatedAt: '2025-02-22',
    isCore: true,
    minGridW: 3,
    minGridH: 5,
  },
  {
    id: 'THEME_ENGINE',
    name: 'Aesthetic Engine',
    description:
      'Live Omni-Grid theme editor — customize colors, fonts, border radius, and glow effects.',
    version: '2.0.0',
    author: 'Omni-Grid Core',
    category: 'creative',
    tags: ['theme', 'design', 'customization'],
    downloads: 11100,
    rating: 4.8,
    updatedAt: '2025-03-01',
    changelog: 'v2.0.0: Complete redesign with real-time preview and theme export/import.',
    isCore: true,
    minGridW: 4,
    minGridH: 6,
  },
  {
    id: 'SONIC',
    name: 'Sonic Architecture',
    description:
      'Ambient sound mixer with brown noise, rain, and custom soundscapes for deep focus.',
    version: '1.3.0',
    author: 'Omni-Grid Core',
    category: 'creative',
    tags: ['sound', 'ambient', 'focus', 'audio'],
    downloads: 8700,
    rating: 4.6,
    updatedAt: '2025-01-30',
    isCore: true,
    minGridW: 4,
    minGridH: 5,
  },
  {
    id: 'SUNO_PLAYER',
    name: 'Suno Player',
    description: 'AI music player and discovery widget integrated with the Suno music platform.',
    version: '1.0.0',
    author: 'Omni-Grid Core',
    category: 'creative',
    tags: ['music', 'ai', 'suno', 'player'],
    downloads: 4200,
    rating: 4.3,
    updatedAt: '2025-03-12',
    isCore: true,
    minGridW: 4,
    minGridH: 8,
  },
  {
    id: 'RADIO',
    name: 'Signal Radio',
    description: 'Global internet radio player with genre filtering and station favorites.',
    version: '1.2.0',
    author: 'Omni-Grid Core',
    category: 'creative',
    tags: ['radio', 'music', 'streaming', 'audio'],
    downloads: 6100,
    rating: 4.3,
    updatedAt: '2025-01-22',
    isCore: true,
    minGridW: 4,
    minGridH: 5,
  },

  // ── AI ────────────────────────────────────────────────────────────────────
  {
    id: 'NEURAL_CHAT',
    name: 'Neural Chat',
    description:
      'Conversational AI assistant powered by Gemini. Context-aware, markdown-rendered responses.',
    version: '2.2.0',
    author: 'Omni-Grid Core',
    category: 'ai',
    tags: ['ai', 'chat', 'gemini', 'assistant'],
    downloads: 18700,
    rating: 4.9,
    updatedAt: '2025-03-15',
    changelog: 'v2.2.0: Multi-turn context, code execution, and conversation export.',
    isCore: true,
    minGridW: 4,
    minGridH: 8,
  },
  {
    id: 'PROMPT_LAB',
    name: 'Prompt Lab',
    description:
      'Prompt engineering workspace with versioning, variable injection, and multi-model testing.',
    version: '1.8.0',
    author: 'Omni-Grid Core',
    category: 'ai',
    tags: ['prompts', 'llm', 'versioning', 'engineering'],
    downloads: 13300,
    rating: 4.8,
    updatedAt: '2025-03-10',
    isCore: true,
    minGridW: 6,
    minGridH: 10,
  },
  {
    id: 'SCRATCHPAD',
    name: 'Neural Scratchpad',
    description:
      'AI-enhanced markdown editor with one-click refine, expand, summarize, and translate actions.',
    version: '2.0.0',
    author: 'Omni-Grid Core',
    category: 'ai',
    tags: ['notes', 'markdown', 'ai', 'writing'],
    downloads: 16400,
    rating: 4.8,
    updatedAt: '2025-02-28',
    isCore: true,
    minGridW: 4,
    minGridH: 6,
  },

  // ── Productivity ──────────────────────────────────────────────────────────
  {
    id: 'FOCUS_HUD',
    name: 'Focus HUD',
    description: 'Task manager with Pomodoro timer, progress tracking, and daily goal streaks.',
    version: '1.5.0',
    author: 'Omni-Grid Core',
    category: 'productivity',
    tags: ['tasks', 'pomodoro', 'productivity', 'focus'],
    downloads: 12100,
    rating: 4.7,
    updatedAt: '2025-02-18',
    isCore: true,
    minGridW: 3,
    minGridH: 5,
  },
  {
    id: 'WRITEPAD',
    name: 'WritePad',
    description: 'Distraction-free long-form writing pad with word count, export, and autosave.',
    version: '1.3.0',
    author: 'Omni-Grid Core',
    category: 'productivity',
    tags: ['writing', 'notes', 'editor', 'markdown'],
    downloads: 7700,
    rating: 4.5,
    updatedAt: '2025-01-25',
    isCore: true,
    minGridW: 4,
    minGridH: 6,
  },
  {
    id: 'SECURE_CALENDAR',
    name: 'Secure Calendar',
    description:
      'Privacy-first calendar with local-only event storage and optional AES-256 encryption.',
    version: '1.4.0',
    author: 'Omni-Grid Core',
    category: 'productivity',
    tags: ['calendar', 'events', 'privacy', 'encrypted'],
    downloads: 6800,
    rating: 4.5,
    updatedAt: '2025-02-02',
    isCore: true,
    minGridW: 4,
    minGridH: 6,
  },
  {
    id: 'ARCHITECT',
    name: 'Widget Architect',
    description:
      'Visual grid layout designer for planning and prototyping Omni-Grid configurations.',
    version: '1.1.0',
    author: 'Omni-Grid Core',
    category: 'productivity',
    tags: ['layout', 'design', 'planning'],
    downloads: 3900,
    rating: 4.2,
    updatedAt: '2025-01-08',
    isCore: true,
    minGridW: 5,
    minGridH: 8,
  },

  // ── Security / Research ────────────────────────────────────────────────────
  {
    id: 'CIPHER_VAULT',
    name: 'Cipher Vault',
    description: 'Password manager with AES-256 encrypted local vault. Zero server-side storage.',
    version: '2.1.0',
    author: 'Omni-Grid Core',
    category: 'utility',
    tags: ['security', 'passwords', 'encryption', 'vault'],
    downloads: 14600,
    rating: 4.9,
    updatedAt: '2025-03-08',
    changelog: 'v2.1.0: Added TOTP/2FA code generation and secure export.',
    isCore: true,
    minGridW: 3,
    minGridH: 5,
  },
  {
    id: 'CIPHER_PAD',
    name: 'Cipher Pad',
    description: 'Encrypted sticky notes with per-note passphrases and clipboard-safe copy.',
    version: '1.2.0',
    author: 'Omni-Grid Core',
    category: 'utility',
    tags: ['security', 'notes', 'encryption'],
    downloads: 5200,
    rating: 4.3,
    updatedAt: '2025-01-20',
    isCore: true,
    minGridW: 3,
    minGridH: 5,
  },
  {
    id: 'NEWS_FEED',
    name: 'News Feed',
    description: 'RSS/Atom feed aggregator with category filtering and read-later queue.',
    version: '1.3.0',
    author: 'Omni-Grid Core',
    category: 'productivity',
    tags: ['rss', 'news', 'feed', 'reader'],
    downloads: 6400,
    rating: 4.2,
    updatedAt: '2025-02-06',
    isCore: true,
    minGridW: 3,
    minGridH: 6,
  },
  {
    id: 'PDF_VIEWER',
    name: 'PDF Viewer',
    description: 'In-grid PDF viewer with page navigation, zoom, and text search.',
    version: '1.1.0',
    author: 'Omni-Grid Core',
    category: 'productivity',
    tags: ['pdf', 'viewer', 'documents'],
    downloads: 4800,
    rating: 4.1,
    updatedAt: '2025-01-15',
    isCore: true,
    minGridW: 4,
    minGridH: 8,
  },
  {
    id: 'RESEARCH_BROWSER',
    name: 'Research Browser',
    description: 'Sandboxed in-grid web browser for research without leaving your workspace.',
    version: '1.2.0',
    author: 'Omni-Grid Core',
    category: 'productivity',
    tags: ['browser', 'research', 'web', 'iframe'],
    downloads: 7500,
    rating: 4.4,
    updatedAt: '2025-02-10',
    isCore: true,
    minGridW: 4,
    minGridH: 8,
  },
  {
    id: 'POLYGLOT',
    name: 'Polyglot Box',
    description: 'Instant translation widget supporting 100+ languages via Google Translate API.',
    version: '1.4.0',
    author: 'Omni-Grid Core',
    category: 'utility',
    tags: ['translation', 'language', 'polyglot'],
    downloads: 5900,
    rating: 4.3,
    updatedAt: '2025-01-28',
    isCore: true,
    minGridW: 3,
    minGridH: 5,
  },

  // ── Community (example entries) ────────────────────────────────────────────
  {
    id: 'GHOST',
    name: 'Ghost Widget',
    description:
      'Placeholder widget for AI-suggested modules. Solidify to replace with the recommended widget.',
    version: '1.0.0',
    author: 'Omni-Grid Core',
    category: 'utility',
    tags: ['ghost', 'placeholder', 'ai-assist'],
    downloads: 0,
    rating: 0,
    updatedAt: '2025-01-01',
    isCore: true,
    minGridW: 3,
    minGridH: 3,
  },
];

/** Lookup a catalog entry by widget ID. Returns undefined if not found. */
export const getCatalogEntry = (id: string): MarketplaceEntry | undefined =>
  MARKETPLACE_CATALOG.find(e => e.id === id);
